### ISSUE TITLE
Fix formatting

### ISSUE THREAD

**Issue by FlamesRunner** [FlamesRunner/MCP#4]
Yeah, formatting could ~use some improvement~ -- who am I kidding? It's awful. Any fixes would be appreciated, particularly on the view files in master/resources/views and the controllers at app/Http/Controllers.

**Comment by sadaimudiNaadhar** [comment]
@FlamesRunner Hello, can I pick this?

**Comment by FlamesRunner** [comment]
Go ahead! Thanks for your help!

**Comment by sadaimudiNaadhar** [comment]
@FlamesRunner  Do we have a platform for communication? Just formatting the code right? (PSR-12)

**Comment by sadaimudiNaadhar** [comment]
@FlamesRunner I will create a sample PR and will update here.

**Comment by FlamesRunner** [comment]
At the moment, there really isn't another platform for communication -- the project is only a few hours old, after all :) I'll look into creating some channel of sorts for exchanges tomorrow or the day after.

In terms of PSR-12, it seems to have exactly what I'm looking for in terms of style and cleanliness, so that would be a good option (and yes, for now just formatting but please feel free to fix any stylistic errors I made).

**Comment by FlamesRunner** [comment]
> @FlamesRunner I will create a sample PR and will update here.

Approved PR for #6, looks great.

**Comment by sadaimudiNaadhar** [comment]
@FlamesRunner  Thank you. Contact me for any kind of help (Open source). Try to avoid magic strings in code. Use DRY, KISS principles.
